### ISSUE TITLE
CLI should return JSON instead of array of json (for --lowest arg )

### ISSUE THREAD

**Issue by yelghali** [Green-Software-Foundation/carbon-aware-sdk#36] opened 2021-12-13 08:22 UTC

**Comment by umairm-tw** [comment] 2022-02-24 10:20
Created PR for resolving this issue
https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/43

**Comment by dylHall** [comment] 2022-08-16 07:59
Hey - can take this one!

**Comment by Willmish** [comment] 2022-08-16 07:59
To be revisited: Needs a JSON object with an array instead of array of JSON objects. (--lowest can still return multiple elements)

**Comment by vaughanknight** [comment] 2022-08-23 07:08
Dylan to discuss with Dan as they we are getting results.  To be discussed this week to find out where the issue is.

NOTE - also add some steps to test / reproduce

**Comment by dylHall** [comment] 2022-08-25 22:11
@Willmish, Happy to continue writing unit tests so that we have coverage of all these cases! I was still a bit confused about how the CLI was working/what the expected output was supposed to be, so that makes a lot more sense. Maybe for the next meeting, we can have a chat about the different scenarios - thinking I'll make a test matrix and we can agree what we think the output should be.

**Comment by dylHall** [comment] 2022-08-25 22:18
@vaughanknight, was chatting with @danuw - and wanted to confirm what the output form of the CLI should be. Based on your comments in another PR, is the expectation that we want to return something like:

{
   emissionsData: [{...EmissionsData}, {...EmissionsData}]
}

Additionally, the current implementation logs to both the console, and the logger. This means there can be two sets of output emitted based on how you're running the CLI (and one of the reasons we might have been seeing discrepancies). Is this still what we want, or should we remove one of the outputs?

**Comment by vaughanknight** [comment] 2022-08-30 07:08
Answer is yes.

**Comment by vaughanknight** [comment] 2022-09-20 07:25
Resolved by #104 and #97

**Closed by vaughanknight** 2022-09-20 07:25 UTC
Labels: bug, good first issue, v1.0
